### ISSUE TITLE
company-anaconda error "JSON-RPC error condition"

### ISSUE THREAD

**Issue by DGalt** [proofit404/company-anaconda#7]
For some reason this doesn't happen for all completions. I can produce it with this though:

`import matplotlib.pyplot as plt`

`plt` (as soon as I hit "." Emacs seizes up for a second and then the following error message is shown):

`Company: Back-end company-anaconda error "JSON-RPC error condition: :message, "Server error", :data, "KeyError(<Nmae: deprecate@244,11>,)", :code, -32000" with args (candidates )`

Output in *anaconda-mode*:

```
Python executable: /usr/bin/python
jedi version: 0.9.0
service_factory version: 0.1.2
anaconda_mode port 9000
127.0.0.1 - - [23/Jun/2015 08:34:40] ================================================================================
Traceback (most recent call last):
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 102, in apply
    result = method(*params)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/anaconda_mode.py", line 61, in wrapper
    return f(Script(source, line, column, path))
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/anaconda_mode.py", line 82, in complete
    for comp in script.completions()]
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/anaconda_mode.py", line 82, in <listcomp>
    for comp in script.completions()]
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/api/classes.py", line 449, in docstring
    followed = self._follow_statements_imports()
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/representation.py", line 591, in __init__
    new_func = helpers.deep_ast_copy(base.base_func, self, self._copy_dict)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/helpers.py", line 64, in deep_ast_copy
    new_obj = copy_node(obj)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/helpers.py", line 55, in copy_node
    new_names_dict[string] = [new_elements[n] for n in names]
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/jedi/evaluate/helpers.py", line 55, in <listcomp>
    new_names_dict[string] = [new_elements[n] for n in names]
KeyError: <Name: deprecate@244,11>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/dan/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "<string>", line 2, in raise_from
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "error": {"message": "Server error", "code": -32000, "data": "KeyError(<Name: deprecate@244,11>,)"}, "id": 10}')

```

This is on Arch linux using Emacs 24.5.1

**Comment by proofit404** [comment]
Try to downgrade your jedi version https://github.com/proofit404/anaconda-mode#attributeerror-and-keyerror-randomly-happens

**Comment by DGalt** [comment]
yup that seems to have taken care of. thanks :)
